# Generated by Django 5.0.4 on 2024-06-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappify_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('date_of_upload', models.DateField()),
                ('unique_photo_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
